#spring:
#  datasource:
#    username: root
#    password: password
#    url: jdbc:mysql://localhost:3306/java_crud
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto:update
#    properties:
